name: SSL Expiry Check

on:
  schedule:
    - cron: '* * * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  ssl_expiry_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SSL expiry check and send alerts
        run: |
          python .github/scripts/ssl_expiry_check.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
